---
components:
  schemas:
    io.k8s.api.authentication.v1.TokenRequestSpec:
      description: TokenRequestSpec contains client provided parameters of a token
        request.
      properties:
        audiences:
          description: Audiences are the intendend audiences of the token. A recipient
            of a token must identitfy themself with an identifier in the list of audiences
            of the token, and otherwise should reject the token. A token issued for
            multiple audiences may be used to authenticate against any of the audiences
            listed but implies a high degree of trust between the target audiences.
          items:
            type: string
          type: array
        boundObjectRef:
          "$ref": "#/components/schemas/io.k8s.api.authentication.v1.BoundObjectReference"
        expirationSeconds:
          description: ExpirationSeconds is the requested duration of validity of
            the request. The token issuer may return a token with a different validity
            duration so a client needs to check the 'expiration' field in a response.
          format: int64
          type: integer
      required:
      - audiences
      type: object
