---
components:
  schemas:
    io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinition:
      description: CustomResourceDefinition represents a resource that should be exposed
        on the API server.  Its name MUST be in the format <.spec.name>.<.spec.group>.
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          "$ref": "#/components/schemas/io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"
        spec:
          "$ref": "#/components/schemas/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec"
        status:
          "$ref": "#/components/schemas/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionStatus"
      required:
      - spec
      type: object
      x-kubernetes-group-version-kind:
      - group: apiextensions.k8s.io
        kind: CustomResourceDefinition
        version: v1
