---
components:
  schemas:
    io.k8s.api.rbac.v1.ClusterRole:
      description: ClusterRole is a cluster level, logical grouping of PolicyRules
        that can be referenced as a unit by a RoleBinding or ClusterRoleBinding.
      properties:
        aggregationRule:
          "$ref": "#/components/schemas/io.k8s.api.rbac.v1.AggregationRule"
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          "$ref": "#/components/schemas/io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"
        rules:
          description: Rules holds all the PolicyRules for this ClusterRole
          items:
            "$ref": "#/components/schemas/io.k8s.api.rbac.v1.PolicyRule"
          type: array
      type: object
      x-kubernetes-group-version-kind:
      - group: rbac.authorization.k8s.io
        kind: ClusterRole
        version: v1
