---
components:
  schemas:
    io.k8s.api.networking.v1beta1.Ingress:
      description: Ingress is a collection of rules that allow inbound connections
        to reach the endpoints defined by a backend. An Ingress can be configured
        to give services externally-reachable urls, load balance traffic, terminate
        SSL, offer name based virtual hosting etc.
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          "$ref": "#/components/schemas/io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"
        spec:
          "$ref": "#/components/schemas/io.k8s.api.networking.v1beta1.IngressSpec"
        status:
          "$ref": "#/components/schemas/io.k8s.api.networking.v1beta1.IngressStatus"
      type: object
      x-kubernetes-group-version-kind:
      - group: networking.k8s.io
        kind: Ingress
        version: v1beta1
