---
components:
  schemas:
    io.k8s.api.storage.v1alpha1.VolumeAttachmentSource:
      description: VolumeAttachmentSource represents a volume that should be attached.
        Right now only PersistenVolumes can be attached via external attacher, in
        future we may allow also inline volumes in pods. Exactly one member can be
        set.
      properties:
        inlineVolumeSpec:
          "$ref": "#/components/schemas/io.k8s.api.core.v1.PersistentVolumeSpec"
        persistentVolumeName:
          description: Name of the persistent volume to attach.
          type: string
      type: object
