---
components:
  schemas:
    io.k8s.api.policy.v1beta1.PodDisruptionBudget:
      description: PodDisruptionBudget is an object to define the max disruption that
        can be caused to a collection of pods
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          "$ref": "#/components/schemas/io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"
        spec:
          "$ref": "#/components/schemas/io.k8s.api.policy.v1beta1.PodDisruptionBudgetSpec"
        status:
          "$ref": "#/components/schemas/io.k8s.api.policy.v1beta1.PodDisruptionBudgetStatus"
      type: object
      x-kubernetes-group-version-kind:
      - group: policy
        kind: PodDisruptionBudget
        version: v1beta1
