---
components:
  schemas:
    io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinitionVersion:
      description: CustomResourceDefinitionVersion describes a version for CRD.
      properties:
        additionalPrinterColumns:
          description: additionalPrinterColumns specifies additional columns returned
            in Table output. See https://kubernetes.io/docs/reference/using-api/api-concepts/#receiving-resources-as-tables
            for details. Top-level and per-version columns are mutually exclusive.
            Per-version columns must not all be set to identical values (top-level
            columns should be used instead). If no top-level or per-version columns
            are specified, a single column displaying the age of the custom resource
            is used.
          items:
            "$ref": "#/components/schemas/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceColumnDefinition"
          type: array
        name:
          description: name is the version name, e.g. “v1”, “v2beta1”, etc. The custom
            resources are served under this version at `/apis/<group>/<version>/...`
            if `served` is true.
          type: string
        schema:
          "$ref": "#/components/schemas/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceValidation"
        served:
          description: served is a flag enabling/disabling this version from being
            served via REST APIs
          type: boolean
        storage:
          description: storage indicates this version should be used when persisting
            custom resources to storage. There must be exactly one version with storage=true.
          type: boolean
        subresources:
          "$ref": "#/components/schemas/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceSubresources"
      required:
      - name
      - served
      - storage
      type: object
