---
components:
  schemas:
    io.k8s.api.coordination.v1beta1.LeaseSpec:
      description: LeaseSpec is a specification of a Lease.
      properties:
        acquireTime:
          "$ref": "#/components/schemas/io.k8s.apimachinery.pkg.apis.meta.v1.MicroTime"
        holderIdentity:
          description: holderIdentity contains the identity of the holder of a current
            lease.
          type: string
        leaseDurationSeconds:
          description: leaseDurationSeconds is a duration that candidates for a lease
            need to wait to force acquire it. This is measure against time of last
            observed RenewTime.
          format: int32
          type: integer
        leaseTransitions:
          description: leaseTransitions is the number of transitions of a lease between
            holders.
          format: int32
          type: integer
        renewTime:
          "$ref": "#/components/schemas/io.k8s.apimachinery.pkg.apis.meta.v1.MicroTime"
      type: object
