---
components:
  schemas:
    io.k8s.api.apps.v1.DaemonSetUpdateStrategy:
      description: DaemonSetUpdateStrategy is a struct used to control the update
        strategy for a DaemonSet.
      properties:
        rollingUpdate:
          "$ref": "#/components/schemas/io.k8s.api.apps.v1.RollingUpdateDaemonSet"
        type:
          description: Type of daemon set update. Can be "RollingUpdate" or "OnDelete".
            Default is RollingUpdate.
          type: string
      type: object
