---
components:
  schemas:
    io.k8s.api.autoscaling.v2beta2.ExternalMetricSource:
      description: ExternalMetricSource indicates how to scale on a metric not associated
        with any Kubernetes object (for example length of queue in cloud messaging
        service, or QPS from loadbalancer running outside of cluster).
      properties:
        metric:
          "$ref": "#/components/schemas/io.k8s.api.autoscaling.v2beta2.MetricIdentifier"
        target:
          "$ref": "#/components/schemas/io.k8s.api.autoscaling.v2beta2.MetricTarget"
      required:
      - metric
      - target
      type: object
