---
components:
  schemas:
    io.k8s.api.autoscaling.v2beta2.HorizontalPodAutoscalerStatus:
      description: HorizontalPodAutoscalerStatus describes the current status of a
        horizontal pod autoscaler.
      properties:
        conditions:
          description: conditions is the set of conditions required for this autoscaler
            to scale its target, and indicates whether or not those conditions are
            met.
          items:
            "$ref": "#/components/schemas/io.k8s.api.autoscaling.v2beta2.HorizontalPodAutoscalerCondition"
          type: array
        currentMetrics:
          description: currentMetrics is the last read state of the metrics used by
            this autoscaler.
          items:
            "$ref": "#/components/schemas/io.k8s.api.autoscaling.v2beta2.MetricStatus"
          type: array
        currentReplicas:
          description: currentReplicas is current number of replicas of pods managed
            by this autoscaler, as last seen by the autoscaler.
          format: int32
          type: integer
        desiredReplicas:
          description: desiredReplicas is the desired number of replicas of pods managed
            by this autoscaler, as last calculated by the autoscaler.
          format: int32
          type: integer
        lastScaleTime:
          "$ref": "#/components/schemas/io.k8s.apimachinery.pkg.apis.meta.v1.Time"
        observedGeneration:
          description: observedGeneration is the most recent generation observed by
            this autoscaler.
          format: int64
          type: integer
      required:
      - currentReplicas
      - desiredReplicas
      - conditions
      type: object
