---
components:
  schemas:
    io.k8s.api.autoscaling.v2beta2.ObjectMetricStatus:
      description: ObjectMetricStatus indicates the current value of a metric describing
        a kubernetes object (for example, hits-per-second on an Ingress object).
      properties:
        current:
          "$ref": "#/components/schemas/io.k8s.api.autoscaling.v2beta2.MetricValueStatus"
        describedObject:
          "$ref": "#/components/schemas/io.k8s.api.autoscaling.v2beta2.CrossVersionObjectReference"
        metric:
          "$ref": "#/components/schemas/io.k8s.api.autoscaling.v2beta2.MetricIdentifier"
      required:
      - metric
      - current
      - describedObject
      type: object
