---
components:
  schemas:
    io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.ExternalDocumentation:
      description: ExternalDocumentation allows referencing an external resource for
        extended documentation.
      properties:
        description:
          type: string
        url:
          type: string
      type: object
