---
components:
  schemas:
    io.k8s.api.policy.v1beta1.IDRange:
      description: IDRange provides a min/max of an allowed range of IDs.
      properties:
        max:
          description: max is the end of the range, inclusive.
          format: int64
          type: integer
        min:
          description: min is the start of the range, inclusive.
          format: int64
          type: integer
      required:
      - min
      - max
      type: object
