---
components:
  schemas:
    io.k8s.api.certificates.v1beta1.CertificateSigningRequestCondition:
      properties:
        lastUpdateTime:
          "$ref": "#/components/schemas/io.k8s.apimachinery.pkg.apis.meta.v1.Time"
        message:
          description: human readable message with details about the request state
          type: string
        reason:
          description: brief reason for the request state
          type: string
        type:
          description: request approval state, currently Approved or Denied.
          type: string
      required:
      - type
      type: object
