---
components:
  schemas:
    io.k8s.apimachinery.pkg.apis.meta.v1.MicroTime:
      description: MicroTime is version of Time with microsecond level precision.
      format: date-time
      type: string
