---
components:
  schemas:
    io.k8s.api.core.v1.Event:
      description: Event is a report of an event somewhere in the cluster.
      properties:
        action:
          description: What action was taken/failed regarding to the Regarding object.
          type: string
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        count:
          description: The number of times this event has occurred.
          format: int32
          type: integer
        eventTime:
          "$ref": "#/components/schemas/io.k8s.apimachinery.pkg.apis.meta.v1.MicroTime"
        firstTimestamp:
          "$ref": "#/components/schemas/io.k8s.apimachinery.pkg.apis.meta.v1.Time"
        involvedObject:
          "$ref": "#/components/schemas/io.k8s.api.core.v1.ObjectReference"
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        lastTimestamp:
          "$ref": "#/components/schemas/io.k8s.apimachinery.pkg.apis.meta.v1.Time"
        message:
          description: A human-readable description of the status of this operation.
          type: string
        metadata:
          "$ref": "#/components/schemas/io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"
        reason:
          description: This should be a short, machine understandable string that
            gives the reason for the transition into the object's current status.
          type: string
        related:
          "$ref": "#/components/schemas/io.k8s.api.core.v1.ObjectReference"
        reportingComponent:
          description: Name of the controller that emitted this Event, e.g. `kubernetes.io/kubelet`.
          type: string
        reportingInstance:
          description: ID of the controller instance, e.g. `kubelet-xyzf`.
          type: string
        series:
          "$ref": "#/components/schemas/io.k8s.api.core.v1.EventSeries"
        source:
          "$ref": "#/components/schemas/io.k8s.api.core.v1.EventSource"
        type:
          description: Type of this event (Normal, Warning), new types could be added
            in the future
          type: string
      required:
      - metadata
      - involvedObject
      type: object
      x-kubernetes-group-version-kind:
      - group: ''
        kind: Event
        version: v1
