---
components:
  schemas:
    io.k8s.api.core.v1.HTTPGetAction:
      description: HTTPGetAction describes an action based on HTTP Get requests.
      properties:
        host:
          description: Host name to connect to, defaults to the pod IP. You probably
            want to set "Host" in httpHeaders instead.
          type: string
        httpHeaders:
          description: Custom headers to set in the request. HTTP allows repeated
            headers.
          items:
            "$ref": "#/components/schemas/io.k8s.api.core.v1.HTTPHeader"
          type: array
        path:
          description: Path to access on the HTTP server.
          type: string
        port:
          "$ref": "#/components/schemas/io.k8s.apimachinery.pkg.util.intstr.IntOrString"
        scheme:
          description: Scheme to use for connecting to the host. Defaults to HTTP.
          type: string
      required:
      - port
      type: object
