---
components:
  schemas:
    io.k8s.api.core.v1.NodeStatus:
      description: NodeStatus is information about the current status of a node.
      properties:
        addresses:
          description: 'List of addresses reachable to the node. Queried from cloud
            provider, if available. More info: https://kubernetes.io/docs/concepts/nodes/node/#addresses
            Note: This field is declared as mergeable, but the merge key is not sufficiently
            unique, which can cause data corruption when it is merged. Callers should
            instead use a full-replacement patch. See http://pr.k8s.io/79391 for an
            example.'
          items:
            "$ref": "#/components/schemas/io.k8s.api.core.v1.NodeAddress"
          type: array
          x-kubernetes-patch-merge-key: type
          x-kubernetes-patch-strategy: merge
        allocatable:
          additionalProperties:
            "$ref": "#/components/schemas/io.k8s.apimachinery.pkg.api.resource.Quantity"
          description: Allocatable represents the resources of a node that are available
            for scheduling. Defaults to Capacity.
          type: object
        capacity:
          additionalProperties:
            "$ref": "#/components/schemas/io.k8s.apimachinery.pkg.api.resource.Quantity"
          description: 'Capacity represents the total resources of a node. More info:
            https://kubernetes.io/docs/concepts/storage/persistent-volumes#capacity'
          type: object
        conditions:
          description: 'Conditions is an array of current observed node conditions.
            More info: https://kubernetes.io/docs/concepts/nodes/node/#condition'
          items:
            "$ref": "#/components/schemas/io.k8s.api.core.v1.NodeCondition"
          type: array
          x-kubernetes-patch-merge-key: type
          x-kubernetes-patch-strategy: merge
        config:
          "$ref": "#/components/schemas/io.k8s.api.core.v1.NodeConfigStatus"
        daemonEndpoints:
          "$ref": "#/components/schemas/io.k8s.api.core.v1.NodeDaemonEndpoints"
        images:
          description: List of container images on this node
          items:
            "$ref": "#/components/schemas/io.k8s.api.core.v1.ContainerImage"
          type: array
        nodeInfo:
          "$ref": "#/components/schemas/io.k8s.api.core.v1.NodeSystemInfo"
        phase:
          description: 'NodePhase is the recently observed lifecycle phase of the
            node. More info: https://kubernetes.io/docs/concepts/nodes/node/#phase
            The field is never populated, and now is deprecated.'
          type: string
        volumesAttached:
          description: List of volumes that are attached to the node.
          items:
            "$ref": "#/components/schemas/io.k8s.api.core.v1.AttachedVolume"
          type: array
        volumesInUse:
          description: List of attachable volumes in use (mounted) by the node.
          items:
            type: string
          type: array
      type: object
