---
components:
  schemas:
    io.k8s.api.core.v1.PersistentVolumeClaimSpec:
      description: PersistentVolumeClaimSpec describes the common attributes of storage
        devices and allows a Source for provider-specific attributes
      properties:
        accessModes:
          description: 'AccessModes contains the desired access modes the volume should
            have. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#access-modes-1'
          items:
            type: string
          type: array
        dataSource:
          "$ref": "#/components/schemas/io.k8s.api.core.v1.TypedLocalObjectReference"
        resources:
          "$ref": "#/components/schemas/io.k8s.api.core.v1.ResourceRequirements"
        selector:
          "$ref": "#/components/schemas/io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector"
        storageClassName:
          description: 'Name of the StorageClass required by the claim. More info:
            https://kubernetes.io/docs/concepts/storage/persistent-volumes#class-1'
          type: string
        volumeMode:
          description: volumeMode defines what type of volume is required by the claim.
            Value of Filesystem is implied when not included in claim spec. This is
            a beta feature.
          type: string
        volumeName:
          description: VolumeName is the binding reference to the PersistentVolume
            backing this claim.
          type: string
      type: object
