---
components:
  schemas:
    io.k8s.api.core.v1.PersistentVolumeClaimCondition:
      description: PersistentVolumeClaimCondition contails details about state of
        pvc
      properties:
        lastProbeTime:
          "$ref": "#/components/schemas/io.k8s.apimachinery.pkg.apis.meta.v1.Time"
        lastTransitionTime:
          "$ref": "#/components/schemas/io.k8s.apimachinery.pkg.apis.meta.v1.Time"
        message:
          description: Human-readable message indicating details about last transition.
          type: string
        reason:
          description: Unique, this should be a short, machine understandable string
            that gives the reason for condition's last transition. If it reports "ResizeStarted"
            that means the underlying persistent volume is being resized.
          type: string
        status:
          type: string
        type:
          type: string
      required:
      - type
      - status
      type: object
