---
components:
  schemas:
    io.k8s.api.core.v1.PodDNSConfigOption:
      description: PodDNSConfigOption defines DNS resolver options of a pod.
      properties:
        name:
          description: Required.
          type: string
        value:
          type: string
      type: object
