---
components:
  schemas:
    io.k8s.api.storage.v1.VolumeAttachmentStatus:
      description: VolumeAttachmentStatus is the status of a VolumeAttachment request.
      properties:
        attachError:
          "$ref": "#/components/schemas/io.k8s.api.storage.v1.VolumeError"
        attached:
          description: Indicates the volume is successfully attached. This field must
            only be set by the entity completing the attach operation, i.e. the external-attacher.
          type: boolean
        attachmentMetadata:
          additionalProperties:
            type: string
          description: Upon successful attach, this field is populated with any information
            returned by the attach operation that must be passed into subsequent WaitForAttach
            or Mount calls. This field must only be set by the entity completing the
            attach operation, i.e. the external-attacher.
          type: object
        detachError:
          "$ref": "#/components/schemas/io.k8s.api.storage.v1.VolumeError"
      required:
      - attached
      type: object
