---
components:
  schemas:
    io.k8s.api.apps.v1beta1.RollingUpdateStatefulSetStrategy:
      description: RollingUpdateStatefulSetStrategy is used to communicate parameter
        for RollingUpdateStatefulSetStrategyType.
      properties:
        partition:
          description: Partition indicates the ordinal at which the StatefulSet should
            be partitioned.
          format: int32
          type: integer
      type: object
