---
components:
  schemas:
    io.k8s.api.apps.v1beta1.RollbackConfig:
      description: DEPRECATED.
      properties:
        revision:
          description: The revision to rollback to. If set to 0, rollback to the last
            revision.
          format: int64
          type: integer
      type: object
