---
components:
  schemas:
    io.k8s.api.autoscaling.v2beta1.HorizontalPodAutoscaler:
      description: HorizontalPodAutoscaler is the configuration for a horizontal pod
        autoscaler, which automatically manages the replica count of any resource
        implementing the scale subresource based on the metrics specified.
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          "$ref": "#/components/schemas/io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"
        spec:
          "$ref": "#/components/schemas/io.k8s.api.autoscaling.v2beta1.HorizontalPodAutoscalerSpec"
        status:
          "$ref": "#/components/schemas/io.k8s.api.autoscaling.v2beta1.HorizontalPodAutoscalerStatus"
      type: object
      x-kubernetes-group-version-kind:
      - group: autoscaling
        kind: HorizontalPodAutoscaler
        version: v2beta1
