---
components:
  requestBodies:
    io.k8s.api.scheduling.v1alpha1.PriorityClass:
      content:
        "*/*":
          schema:
            "$ref": "#/components/schemas/io.k8s.api.scheduling.v1alpha1.PriorityClass"
      required: true
