---
components:
  schemas:
    io.k8s.api.storage.v1alpha1.VolumeAttachmentSpec:
      description: VolumeAttachmentSpec is the specification of a VolumeAttachment
        request.
      properties:
        attacher:
          description: Attacher indicates the name of the volume driver that MUST
            handle this request. This is the name returned by GetPluginName().
          type: string
        nodeName:
          description: The node that the volume should be attached to.
          type: string
        source:
          "$ref": "#/components/schemas/io.k8s.api.storage.v1alpha1.VolumeAttachmentSource"
      required:
      - attacher
      - source
      - nodeName
      type: object
