---
components:
  schemas:
    io.k8s.api.storage.v1beta1.VolumeAttachment:
      description: |-
        VolumeAttachment captures the intent to attach or detach the specified volume to/from the specified node.

        VolumeAttachment objects are non-namespaced.
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          "$ref": "#/components/schemas/io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"
        spec:
          "$ref": "#/components/schemas/io.k8s.api.storage.v1beta1.VolumeAttachmentSpec"
        status:
          "$ref": "#/components/schemas/io.k8s.api.storage.v1beta1.VolumeAttachmentStatus"
      required:
      - spec
      type: object
      x-kubernetes-group-version-kind:
      - group: storage.k8s.io
        kind: VolumeAttachment
        version: v1beta1
