---
components:
  schemas:
    io.k8s.api.authorization.v1.SelfSubjectAccessReviewSpec:
      description: SelfSubjectAccessReviewSpec is a description of the access request.  Exactly
        one of ResourceAuthorizationAttributes and NonResourceAuthorizationAttributes
        must be set
      properties:
        nonResourceAttributes:
          "$ref": "#/components/schemas/io.k8s.api.authorization.v1.NonResourceAttributes"
        resourceAttributes:
          "$ref": "#/components/schemas/io.k8s.api.authorization.v1.ResourceAttributes"
      type: object
