---
components:
  schemas:
    io.k8s.api.admissionregistration.v1.ValidatingWebhook:
      description: ValidatingWebhook describes an admission webhook and the resources
        and operations it applies to.
      properties:
        admissionReviewVersions:
          description: AdmissionReviewVersions is an ordered list of preferred `AdmissionReview`
            versions the Webhook expects. API server will try to use first version
            in the list which it supports. If none of the versions specified in this
            list supported by API server, validation will fail for this object. If
            a persisted webhook configuration specifies allowed versions and does
            not include any versions known to the API Server, calls to the webhook
            will fail and be subject to the failure policy.
          items:
            type: string
          type: array
        clientConfig:
          "$ref": "#/components/schemas/io.k8s.api.admissionregistration.v1.WebhookClientConfig"
        failurePolicy:
          description: FailurePolicy defines how unrecognized errors from the admission
            endpoint are handled - allowed values are Ignore or Fail. Defaults to
            Fail.
          type: string
        matchPolicy:
          description: |-
            matchPolicy defines how the "rules" list is used to match incoming requests. Allowed values are "Exact" or "Equivalent".

            - Exact: match a request only if it exactly matches a specified rule. For example, if deployments can be modified via apps/v1, apps/v1beta1, and extensions/v1beta1, but "rules" only included `apiGroups:["apps"], apiVersions:["v1"], resources: ["deployments"]`, a request to apps/v1beta1 or extensions/v1beta1 would not be sent to the webhook.

            - Equivalent: match a request if modifies a resource listed in rules, even via another API group or version. For example, if deployments can be modified via apps/v1, apps/v1beta1, and extensions/v1beta1, and "rules" only included `apiGroups:["apps"], apiVersions:["v1"], resources: ["deployments"]`, a request to apps/v1beta1 or extensions/v1beta1 would be converted to apps/v1 and sent to the webhook.

            Defaults to "Equivalent"
          type: string
        name:
          description: The name of the admission webhook. Name should be fully qualified,
            e.g., imagepolicy.kubernetes.io, where "imagepolicy" is the name of the
            webhook, and kubernetes.io is the name of the organization. Required.
          type: string
        namespaceSelector:
          "$ref": "#/components/schemas/io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector"
        objectSelector:
          "$ref": "#/components/schemas/io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector"
        rules:
          description: Rules describes what operations on what resources/subresources
            the webhook cares about. The webhook cares about an operation if it matches
            _any_ Rule. However, in order to prevent ValidatingAdmissionWebhooks and
            MutatingAdmissionWebhooks from putting the cluster in a state which cannot
            be recovered from without completely disabling the plugin, ValidatingAdmissionWebhooks
            and MutatingAdmissionWebhooks are never called on admission requests for
            ValidatingWebhookConfiguration and MutatingWebhookConfiguration objects.
          items:
            "$ref": "#/components/schemas/io.k8s.api.admissionregistration.v1.RuleWithOperations"
          type: array
        sideEffects:
          description: 'SideEffects states whether this webhook has side effects.
            Acceptable values are: None, NoneOnDryRun (webhooks created via v1beta1
            may also specify Some or Unknown). Webhooks with side effects MUST implement
            a reconciliation system, since a request may be rejected by a future step
            in the admission change and the side effects therefore need to be undone.
            Requests with the dryRun attribute will be auto-rejected if they match
            a webhook with sideEffects == Unknown or Some.'
          type: string
        timeoutSeconds:
          description: TimeoutSeconds specifies the timeout for this webhook. After
            the timeout passes, the webhook call will be ignored or the API call will
            fail based on the failure policy. The timeout value must be between 1
            and 30 seconds. Default to 10 seconds.
          format: int32
          type: integer
      required:
      - name
      - clientConfig
      - sideEffects
      - admissionReviewVersions
      type: object
