---
components:
  schemas:
    io.k8s.api.autoscaling.v2beta1.PodsMetricSource:
      description: PodsMetricSource indicates how to scale on a metric describing
        each pod in the current scale target (for example, transactions-processed-per-second).
        The values will be averaged together before being compared to the target value.
      properties:
        metricName:
          description: metricName is the name of the metric in question
          type: string
        selector:
          "$ref": "#/components/schemas/io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector"
        targetAverageValue:
          "$ref": "#/components/schemas/io.k8s.apimachinery.pkg.api.resource.Quantity"
      required:
      - metricName
      - targetAverageValue
      type: object
