---
components:
  schemas:
    io.k8s.api.core.v1.ContainerState:
      description: ContainerState holds a possible state of container. Only one of
        its members may be specified. If none of them is specified, the default one
        is ContainerStateWaiting.
      properties:
        running:
          "$ref": "#/components/schemas/io.k8s.api.core.v1.ContainerStateRunning"
        terminated:
          "$ref": "#/components/schemas/io.k8s.api.core.v1.ContainerStateTerminated"
        waiting:
          "$ref": "#/components/schemas/io.k8s.api.core.v1.ContainerStateWaiting"
      type: object
