---
components:
  schemas:
    io.k8s.api.core.v1.ContainerStateTerminated:
      description: ContainerStateTerminated is a terminated state of a container.
      properties:
        containerID:
          description: Container's ID in the format 'docker://<container_id>'
          type: string
        exitCode:
          description: Exit status from the last termination of the container
          format: int32
          type: integer
        finishedAt:
          "$ref": "#/components/schemas/io.k8s.apimachinery.pkg.apis.meta.v1.Time"
        message:
          description: Message regarding the last termination of the container
          type: string
        reason:
          description: "(brief) reason from the last termination of the container"
          type: string
        signal:
          description: Signal from the last termination of the container
          format: int32
          type: integer
        startedAt:
          "$ref": "#/components/schemas/io.k8s.apimachinery.pkg.apis.meta.v1.Time"
      required:
      - exitCode
      type: object
