---
components:
  schemas:
    io.k8s.api.core.v1.CSIPersistentVolumeSource:
      description: Represents storage that is managed by an external CSI volume driver
        (Beta feature)
      properties:
        controllerExpandSecretRef:
          "$ref": "#/components/schemas/io.k8s.api.core.v1.SecretReference"
        controllerPublishSecretRef:
          "$ref": "#/components/schemas/io.k8s.api.core.v1.SecretReference"
        driver:
          description: Driver is the name of the driver to use for this volume. Required.
          type: string
        fsType:
          description: Filesystem type to mount. Must be a filesystem type supported
            by the host operating system. Ex. "ext4", "xfs", "ntfs".
          type: string
        nodePublishSecretRef:
          "$ref": "#/components/schemas/io.k8s.api.core.v1.SecretReference"
        nodeStageSecretRef:
          "$ref": "#/components/schemas/io.k8s.api.core.v1.SecretReference"
        readOnly:
          description: 'Optional: The value to pass to ControllerPublishVolumeRequest.
            Defaults to false (read/write).'
          type: boolean
        volumeAttributes:
          additionalProperties:
            type: string
          description: Attributes of the volume to publish.
          type: object
        volumeHandle:
          description: VolumeHandle is the unique volume name returned by the CSI
            volume plugin’s CreateVolume to refer to the volume on all subsequent
            calls. Required.
          type: string
      required:
      - driver
      - volumeHandle
      type: object
