---
components:
  schemas:
    io.k8s.api.core.v1.FlexVolumeSource:
      description: FlexVolume represents a generic volume resource that is provisioned/attached
        using an exec based plugin.
      properties:
        driver:
          description: Driver is the name of the driver to use for this volume.
          type: string
        fsType:
          description: Filesystem type to mount. Must be a filesystem type supported
            by the host operating system. Ex. "ext4", "xfs", "ntfs". The default filesystem
            depends on FlexVolume script.
          type: string
        options:
          additionalProperties:
            type: string
          description: 'Optional: Extra command options if any.'
          type: object
        readOnly:
          description: 'Optional: Defaults to false (read/write). ReadOnly here will
            force the ReadOnly setting in VolumeMounts.'
          type: boolean
        secretRef:
          "$ref": "#/components/schemas/io.k8s.api.core.v1.LocalObjectReference"
      required:
      - driver
      type: object
