---
components:
  schemas:
    io.k8s.api.core.v1.PreferredSchedulingTerm:
      description: An empty preferred scheduling term matches all objects with implicit
        weight 0 (i.e. it's a no-op). A null preferred scheduling term matches no
        objects (i.e. is also a no-op).
      properties:
        preference:
          "$ref": "#/components/schemas/io.k8s.api.core.v1.NodeSelectorTerm"
        weight:
          description: Weight associated with matching the corresponding nodeSelectorTerm,
            in the range 1-100.
          format: int32
          type: integer
      required:
      - weight
      - preference
      type: object
