---
components:
  schemas:
    io.k8s.api.core.v1.ResourceQuota:
      description: ResourceQuota sets aggregate quota restrictions enforced per namespace
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          "$ref": "#/components/schemas/io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"
        spec:
          "$ref": "#/components/schemas/io.k8s.api.core.v1.ResourceQuotaSpec"
        status:
          "$ref": "#/components/schemas/io.k8s.api.core.v1.ResourceQuotaStatus"
      type: object
      x-kubernetes-group-version-kind:
      - group: ''
        kind: ResourceQuota
        version: v1
