---
components:
  schemas:
    io.k8s.api.core.v1.ResourceFieldSelector:
      description: ResourceFieldSelector represents container resources (cpu, memory)
        and their output format
      properties:
        containerName:
          description: 'Container name: required for volumes, optional for env vars'
          type: string
        divisor:
          "$ref": "#/components/schemas/io.k8s.apimachinery.pkg.api.resource.Quantity"
        resource:
          description: 'Required: resource to select'
          type: string
      required:
      - resource
      type: object
