---
components:
  schemas:
    io.k8s.api.core.v1.Service:
      description: Service is a named abstraction of software service (for example,
        mysql) consisting of local port (for example 3306) that the proxy listens
        on, and the selector that determines which pods will answer requests sent
        through the proxy.
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          "$ref": "#/components/schemas/io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"
        spec:
          "$ref": "#/components/schemas/io.k8s.api.core.v1.ServiceSpec"
        status:
          "$ref": "#/components/schemas/io.k8s.api.core.v1.ServiceStatus"
      type: object
      x-kubernetes-group-version-kind:
      - group: ''
        kind: Service
        version: v1
