---
components:
  schemas:
    io.k8s.api.core.v1.Taint:
      description: The node this Taint is attached to has the "effect" on any pod
        that does not tolerate the Taint.
      properties:
        effect:
          description: Required. The effect of the taint on pods that do not tolerate
            the taint. Valid effects are NoSchedule, PreferNoSchedule and NoExecute.
          type: string
        key:
          description: Required. The taint key to be applied to a node.
          type: string
        timeAdded:
          "$ref": "#/components/schemas/io.k8s.apimachinery.pkg.apis.meta.v1.Time"
        value:
          description: Required. The taint value corresponding to the taint key.
          type: string
      required:
      - key
      - effect
      type: object
