---
components:
  schemas:
    io.k8s.api.batch.v2alpha1.CronJob:
      description: CronJob represents the configuration of a single cron job.
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          "$ref": "#/components/schemas/io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"
        spec:
          "$ref": "#/components/schemas/io.k8s.api.batch.v2alpha1.CronJobSpec"
        status:
          "$ref": "#/components/schemas/io.k8s.api.batch.v2alpha1.CronJobStatus"
      type: object
      x-kubernetes-group-version-kind:
      - group: batch
        kind: CronJob
        version: v2alpha1
