---
components:
  schemas:
    io.k8s.api.autoscaling.v2beta2.PodsMetricStatus:
      description: PodsMetricStatus indicates the current value of a metric describing
        each pod in the current scale target (for example, transactions-processed-per-second).
      properties:
        current:
          "$ref": "#/components/schemas/io.k8s.api.autoscaling.v2beta2.MetricValueStatus"
        metric:
          "$ref": "#/components/schemas/io.k8s.api.autoscaling.v2beta2.MetricIdentifier"
      required:
      - metric
      - current
      type: object
