---
components:
  requestBodies:
    io.k8s.api.auditregistration.v1alpha1.AuditSink:
      content:
        "*/*":
          schema:
            "$ref": "#/components/schemas/io.k8s.api.auditregistration.v1alpha1.AuditSink"
      required: true
